Stroimaterial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField("Категория", max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField("Название", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField("Изображение", upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField("Описание", blank=True)
    price = models.DecimalField("Цена", max_digits=10, decimal_places=2)
    available = models.BooleanField("В наличии", default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail',
                           args=[self.id, self.slug])

orders/models.py
from django.db import models
from main.models import Product


class Order(models.Model):
    first_name = models.CharField("Имя", max_length=50)
    last_name = models.CharField("Фамилия", max_length=50)
    email = models.EmailField()
    address = models.CharField("Адрес", max_length=250)
    postal_code = models.CharField("Почтовый индекс", max_length=20)
    city = models.CharField("Город", max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField("Количество", default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                              initial={'quantity': item['quantity'],
                              'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category_page = None
    products = None
    if category_slug != None:
        category_page = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category_page, available=True)
    else:
        products = Product.objects.all().filter(available=True)
    return render(request,
                  'shop/product/list.html',
                  {'category': category_page,
                   'products': products,
                   })

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Script for dropdown-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <style type='text/css'>
      .material-icons.md-48 { font-size: 48px; }
      .material-icons.md-24 { font-size: 24px; }
      table {border: 1px solid;}
      td {border: 1px solid;}
    </style>
    <title>
       {% block title %}
       {% endblock %}
    </title>
  </head>

  <body>


    {% include 'navbar.html' %}
  
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>

templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Товары в корзине</h1>
  <table>
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за один товар</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }}руб</td>
            <td class="num">{{ item.total_price }}руб</td>
          </tr>
        {% endwith %}
      {% endfor %}
    </tbody>
  </table>
    <h2>Итого {{ cart.get_total_price }}</h2>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">Продилжить закупку</a>
    <a href="{% url "orders:order_create" %}" class="button">
      Оформить заказ
    </a>
  </p>
{% endblock %}

templates/footer.html
<footer class='bg-dark text-white mt-5 p-5'>
  <div class="container">
    <p class="lead text-center">Стройматериалы &copy; 2020</p>
  </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-dark">
  <a href="{% url 'shop:product_list' %}" class="navbar-brand"><i class='material-icons text-success md-48'>store</i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
   <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
  <ul class="navbar-nav">
    <li class="nav-item dropdown"><a class="nav-link text-light text-uppercase font-weight-bold px-3 dropdown-toggle" data-toggle="dropdown" href="">Категории</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'shop:product_list' %}">Все товары</a>
      {% for category in links %}
        <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
      {% endfor %}
    </div>
    <li class="nav-item"><a class="nav-link text-light text-uppercase font-weight-bold px-3" href="">Контакты</a></li>
    <li class="nav-item"><a class="nav-link text-light text-uppercase font-weight-bold px-3" href="">О нас</a></li>
  </ul>

  <form class="form-inline">
    <div class="input-group">
      <input type="text" placeholder="Search">
      <div>
        <button class="btn-success"><i class='material-icons md-24'>search</i></button>
      </div>
    </div>
  </form>
</div>
</nav>

templates/orders/order/create.html
{% extends "base.html" %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}
  <h1>Оформление заказа</h1>

  <div class="order-info">
    <h3>Ваш заказ</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }}
          <span>{{ item.total_price }}руб</span>
        </li>
      {% endfor %}
    </ul>
    <p>Total: {{ cart.get_total_price }}руб</p>
  </div>

  <form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Заказать"></p>
    {% csrf_token %}
  </form>
{% endblock %}

templates/orders/order/created.html
{% extends "base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}
  <h1>Спасибо</h1>
  <p>Ваш закакз успешно оформлен. Ваш номер: <strong>{{ order.id }}</strong>.</p>
{% endblock %}

templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
	<div class="container py-5">
		<div class="row mt-5">
			<div class="col-10 mx-auto col-md-6 my-3">
				<img src="{{product.image.url}}">
			</div>
		</div>
	</div>
	<div class="col-10 mx-auto col-md-6 my-3">
		<div>
			<h1 class="product_title">{{ product.name }}</h1>
            <p class="product_desc">Описание</p>
			<p class="text-justify product_text">{{ product.description}}</p>
			<h5 class="text-info font-italic mb-4">{{ product.price }}</h5>
            <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
            </form>
        </div>
    </div>
{% endblock %}

templates/shop/product/list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Home
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
			<img class="img-fluid" src="{% static 'images/main_img.jpg' %}" width="100%">
		</div>
	</div>

	<div class="py-4">
		<div class="container">
			<div class="row">
				<div class="col-10 mx-auto my-2 text-center">
					<h1 class="text-capitalize font-weight-bold">
						Наши товары
					</h1>
				</div>
			</div>
		</div>

	</div>

	<div class="container">
		<div class="row">
			{% for product in products %}
				<div class="col-9 mx-auto col-md-6 col-lg-3">
					<div class="card mb-5">
						<div class="p-4">
							<a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}"></a>

						</div>

						<div class="card-footer d-flex justify-content-between" style="background: transparent; border-color: transparent;">
							<p class="font-weight-bold mb-0">
								{{ product.name|truncatewords:6|safe }}
							</p>
							<h5 class="text-info font-italic mb-0">
								{{ product.price }}
							</h5>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>


{% endblock %}